name: Automate Cypress Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --save-dev cypress

      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npx cypress run
          wait-on: 'http://localhost:3000'
          runTests: true
